name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn install
    - name: Deploy to GH Pages
      env:
        DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "i@llc.moe"
        git config --global user.name "粒粒橙"
        git remote set-url origin https://$DEPLOY_TOKEN@github.com/llc1123/animators-stopwatch.git
        yarn run deploy